### PR TITLE
Flyingcarpet Proposal

### PR DESCRIPTION
**Pull request by leopoldjoy**
Please let me know if there is any additional information that would be useful for us to provide.

Thank you for your consideration!

### CODE REVIEW

**Comment by MareenG** [comment]
@leopoldjoy 
Thanks for the proposal it looks like a really interesting project. 
Would you and your team be up for a quick call the next days?

**Comment by leopoldjoy** [comment]
Hi @MareenG,
Thanks for your response. Yes, a call sounds great! Our team is spilt between Europe and the US. How about Thursday at 4pm CST / 10am EST?

Is there anything specific you'll want to focus on in the call?

Look forward to chatting!
Best, Leo

**Comment by MareenG** [comment]
Hi @leopoldjoy 
I have already meeting during that time. 
I only could do earlier before 4pm CEST or on Friday 5pm CEST.
I mainly want to mainly speak about how you want to integrate the prediction markets within your platform and which markets you envision to be asked within your project. 

Best wishes, 
Mareen

**Comment by leopoldjoy** [comment]
Hi @MareenG,
Friday at 5pm CEST works well. Thanks for the info, sounds good.

Look forward to chatting!
Best,
Leo

**Comment by MareenG** [comment]
Hey @leopoldjoy, 
Sorry for the back and forth I can't make today at 5pm anymore. 
Could we do Monday at 5pm and I will reserve this spot for now. 
Could you send me an email to GECO@gnosis.pm and I will send you an invite. 

Best wishes, 
Mareen

**Comment by leopoldjoy** [comment]
Hi @MareenG,
No worries. Would Monday at 2pm CEST be possible? Our CEO, Julien, will be busy later in the day at the World Economic Forum in Davos.
Best,
Leo

**Comment by MareenG** [comment]
@leopoldjoy 
Yes that works aswell. Could you send me an email or an invite. 
Looking forward to the call,
Mareen

**Comment by leopoldjoy** [comment]
@MareenG Perfect! Invite sent.
Talk then,
Leo

**Comment by leopoldjoy** [comment]
Let's talk here: https://hangouts.google.com/call/KYGIesTdCVjG4dlTcdN4AEEE

**Pull request merged**
