### PR TITLE
Tokenary Shared Account Proposal

### PR DESCRIPTION
**Pull request by rockfridrich**
We want to give users the ability to use shared accounts to manage their crypto assets. Setting up a shared account to hold Ethereum assets is a tricky process now. Besides additional security that a shared account gives, it allows users to manage their funds together which is hard to do within the existent financial infrastructure (i.e. bank accounts). Using our existing software, iOS, macOS and web wallet interfaces, we want to provide our users with the best user experience. We want to make the process of submitting and confirming transactions as fast and convenient as possible.

### CODE REVIEW

**Comment by MareenG** [comment]
Hey @rockfridrich, 
Thank you for submitting your proposal. 
I will go through it and give you a first feedback in the next days. 
Your propsal will be part of the next wave of grants (submission deadline 31.3.2019).

Best wishes, 
Mareen

**Comment by rockfridrich** [comment]
Hey @MareenG,

We will be waiting for your feedback 👍 
Does the first wave of projects already finalize?

**Comment by GnosisEcosystemFund** [comment]
@rockfridrich 
Unfortunately, you just missed the December round. We are planning to announce the first grantees soon. But your proposal will be considered in the next round. 
Concerning your proposal. It sounds quite clear and structured to me. However, I would like to aks you if you could iterate a bit how your projects fits within the Gnosis Ecosystem. As I understood you are planning to build a safe wallet, will you include the Safe smart contracts? How will it be positioned in respect to the Gnosis Safe? It would be great if you could iterate a bit on this aspect. 

Best wishes, 
Mareen

**Comment by rockfridrich** [comment]
Hey @MareenG,

Thanks for letting me know. When is the next round of grants scheduled to begin?

You understood correctly. We plan to build shared account functionality based on Gnosis tech. Consequently, we will ensure that Tokenary is compatible with Safe so users will be able to transition between wallets as needed. We will also make sure users are aware that the shared account is powered by Gnosis tech.

We see Gnosis Safe as a partner wallet rather than a competitor—especially since we are both tackling different market segments.
Please let me know if you have any other questions.

Vadim

**Comment by grachyov** [comment]
Hey @MareenG @GnosisEcosystemFund,

Hope you are doing well. We have released a Safari extension, it's available [on the App Store](http://tokenary.io/macos). It brings Ethereum dapps to Safari users in a nice native interface. Also, our team has won [0x hackathon](https://medium.com/coinlist/announcing-the-winners-of-the-0x-coinlist-hackathon-c4bc8ff4f79d). We have built a feature to swap NFTs between nearby devices.

Just curious about the status of our application. Are there any updates?

Regards,
Ivan

**Comment by MareenG** [comment]
@rockfridrich 
We are currently planning the pitch event for April 17th. 
Could you reach out to GECO@gnosis.pm to schedule your slot. 
Best wishes, 
Mareen

**Comment by rockfridrich** [comment]
Hi @MareenG,
Thank you for inviting us to join this event. I sent you an email. 
Regards,
Vadim

**Pull request merged**
