### PR TITLE
Sablier Safe App proposal

### PR DESCRIPTION
**Pull request by PaulRBerg**
Proposal to build a Safe App that interacts with the [Sablier dapp](https://pay.sablier.finance).

Team: myself and @TomAFrench.

### CODE REVIEW

**Comment by GnosisEcosystemFund** [comment]
Hey Paul, awesome! Do you still need input from us? Otherwise please go ahead! Also, what's the best way to reach you? :)

**Comment by PaulRBerg** [comment]
Cool, we don't need any other support for now. The docs were pretty much self-explanatory!

I'm `PaulRBerg#7401` on Discord and @TomAFrench is `Tom French#3331`. We've both joined your community server.

**Comment by PaulRBerg** [comment]
We have an MVP ready for prime time 🔥

+ Vercel URL: https://sablier-safe-app.now.sh/
+ IPFS URL: https://ipfs.io/ipfs/QmdUDnyvnna7N3XKwb8aaFka5z6j1oAypRrnZY8vMXJifM/

I attached two screen captures for how the app looks like. Features available:

1. Create streams with arbitrary streaming durations. The start time is implicitly set to 1 hour from the present time, and this cannot be changed, but we think this is a sensible default considering the current gas prices on Ethereum.
2. Cancel active streams.

The recipient is supposed to claim their earnings on [app.sablier.finance](https://app.sablier.finance), but this is the same user flow as in our canonical [stream creation dapp](https://pay.sablier.finance).

The source can be found at https://github.com/tomafrench/sablier-safe-app. We're looking forward to hearing your comments, suggestions and ideas :)

| | | 
|:-------------------------:|:-------------------------:|
|Sablier Safe App Screen Capture #1  Create Stream |  screen shot 2017-08-07 at 12 18 15 pm Manage Created Streams |

**Comment by TomAFrench** [comment]
Here's the updated IPFS URL for the new version.

IPFS URL: https://ipfs.io/ipfs/QmTRFQnvt1p3EXJYbKqyPTUby5Wj4gBoQG6CpRRvCDMhiS/

**Comment by TomAFrench** [comment]
And once again: https://ipfs.io/ipfs/QmaH2iMyKUGBAwnovYZkM3h32wr3MCdM7CBXJCLKsSv5q9/

**Pull request merged**
