### PR TITLE
Diadem.Network

### PR DESCRIPTION
**Pull request by 7flash**
Allow making transparent charitable donations using Gnosis cryptocurrency

### CODE REVIEW

**Comment by MareenG** [comment]
Hey @7flash, 
Thanks for the proposal. I went through it and the main idea sounds good but I also have a few open questions. Would you be up for a call to discuss the project a bit more. 
Best wishes, 
Mareen

**Comment by 7flash** [comment]
Thanks, please, schedule a call for your available time, and reach us team@diadem.network

**Comment by MareenG** [comment]
@7flash I send an invite le tme know if this works. 
If not just propose a new one.

**Comment by MareenG** [comment]
@7flash I guess you missed the call today. Let me know if you are interested in a new one?

**Pull request merged**
